[platformio]
default_envs = firmware

[env:firmware]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
lib_deps =
    https://github.com/MatheusAlvesA/ArduinoAsync.git
    https://github.com/J-A-A-M/melody-player.git@2.4.0
    adafruit/Adafruit NeoPixel@1.15.4
    yasheena/TelnetSpy@1.4
    tzapu/WiFiManager@2.0.17
    bblanchon/ArduinoJson@7.4.2
    gilmaimon/ArduinoWebsockets@0.5.4
    denyschuhlib/NTPtime@1.2.1
    olikraus/U8g2@2.36.17
    sensirion/arduino-sht@1.2.6
    https://github.com/enjoyneering/AHTxx.git@1.2.0
	soylentorange/forcedBMX280@1.1.1
    wollewald/BH1750_WE@1.1.10
	dfrobot/DFRobot_DF1201S@^1.0.2
    mathertel/OneButton@2.6.2
build_flags =
    -D ARDUINO_ESP32_DEV
    -D BME280_ENABLED
	-D SHT2X_ENABLED
	-D SHT3X_ENABLED
    -D AHTXX_ENABLED
	-D BH1750_ENABLED
    -D BUZZER_ENABLED
	-D DFPLAYER_PRO_ENABLED
    -D VERSION=\"5.0\"
    -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000 # (keep default)
    -D CONFIG_ASYNC_TCP_PRIORITY=10 # (keep default)
    -D CONFIG_ASYNC_TCP_QUEUE_SIZE=64 # (keep default)
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1

[env:test_animation]
extends = env:firmware
build_flags =
    ${env:firmware.build_flags}
    -D TEST_ANIMATION

[env:test_min_of_silence]
extends = env:firmware
build_flags =
    ${env:firmware.build_flags}
    -D TEST_MIN_OF_SILENCE

[env:firmware_esp32s3]
extends = env:firmware
board = esp32-s3-devkitc-1
monitor_speed = 115200

[env:firmware_esp32s3_4mb]
extends = env:firmware_esp32s3
board_build.flash_size = 4MB
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.partitions = custom_4MB.csv

[env:firmware_esp32s3_matrix]
extends = env:firmware
board = lolin_s3_mini
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.flash_mode = dio
board_build.partitions = custom_4MB.csv

[env:firmware_esp32c3]
extends = env:firmware
board = esp32-c3-devkitc-02